"""Add unique constraint to departments

Revision ID: c2ca61bf4baf
Revises: 3783d1cae949
Create Date: 2026-01-18 22:07:55.699157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2ca61bf4baf'
down_revision = '3783d1cae949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_unique_constraint('uq_department_org_name', ['organization_id', 'name'])
        batch_op.drop_constraint(batch_op.f('departments_owner_id_fkey'), type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('is_default')
        batch_op.drop_column('config')
        batch_op.drop_column('is_custom')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('departments_owner_id_fkey'), 'users', ['owner_id'], ['id'])
        batch_op.drop_constraint('uq_department_org_name', type_='unique')
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
