"""Enhance activity model with priority and assignment

Revision ID: cdaaa5a7533a
Revises: c2ca61bf4baf
Create Date: 2026-01-20 11:38:09.025249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdaaa5a7533a'
down_revision = 'c2ca61bf4baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('execution_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('execution_data')
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
